---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "Add nodejs from Nodesource"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
- name: "Install nodejs"
  become: true
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes

- name: "Globally install pm2"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present