---
- name: "update packages."
  become: true
  apt:
    update_cache: "yes"

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: install node 
  shell: |
    curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash - && sudo apt-get install -y nodejs npm

- name: "install python."
  become: true
  apt:
    name: python3
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present