---
- name: Creates directory
  file:
    path: ~/web
    state: directory
- name: "Unarchive backend files to backend-app directory"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Install node dependencies"
  shell: |
    cd ~/backend-app
    npm install
- name: "Execute node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: "Debug"
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure PM2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu