---
- name: Creates directory
  file:
    path: ~/backend
    state: directory
- name: "Unarchive backend files to backend-app directory"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend
- name: "Configure PM2 to start as service"
  become: true
  shell: |
    cd ~/backend
    npm install
    npm run build
    npm run start:prod
    #pm2 stop default
    #pm2 start npm -- start