---
- name: Creates directory
  file:
    path: ~/backend-app
    state: directory
- name: "Unarchive backend files to backend-app directory"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app
- name: "Configure PM2 to start as service"
  become: true
  shell: |
    cd ~/backend-app
    pm2 stop default
    pm2 start npm -- start