---
- name: Creates directory
  file:
    path: ~/web
    state: directory
- name: "Update node to 13.X"
  shell: |
     curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
     sudo apt-get install nodejs -y

- name: "Extract backend files to EC2"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: Executing node
  shell: |
    cd ~/web
    pm2 stop default
    pm2 start npm -- start