---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: install node 
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash - && sudo apt-get install -y nodejs13 npm

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: "backend.tar.gz"
    dest: "~/"

- name: Executing node
  shell: |
    ls
    npm install
    pm2 stop default
    pm2 start npm -- start