---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: Copy index test page
  copy:
    src: "backend.tar.gz"
    dest: "."
    remote_src: yes
    

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: "backend.tar.gz"
    dest: "."

- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start