---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: "backend.tar.gz"
    dest: "~/"

- name: Executing node
  shell: |
    ls
    npm install
    npm build
    pm2 stop default
    pm2 start npm -- start