---
#- name: Creates directory
#  file:
#    path: ~/backend
#    state: directory
- name: "Unarchive backend files to backend-app directory"
  unarchive:
    src: artifact.tar.gz
    dest: ~/
- name: "Configure PM2 to start as service"
  become: true
  shell: |
    npm i
    pm2 stop default
    pm2 start npm -- start