---

- name: "Create backend-app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files to backend-app directory"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app
# - name: "Execute node app with PM2"
#   shell: |
#      cd ~/backend-app
#      export NODE_ENV=local
#      export VERSION=1
#      export TYPEORM_CONNECTION=postgres
#      export TYPEORM_MIGRATIONS_DIR=./src/migrations
#      export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
#      export TYPEORM_MIGRATIONS=./src/migrations/*.ts
#      export TYPEORM_HOST=databasenewer.cnddcmishdty.us-east-1.rds.amazonaws.com
#      export TYPEORM_PORT=5432
#      export TYPEORM_USERNAME=postgres
#      export TYPEORM_PASSWORD=postgres
#      export TYPEORM_DATABASE=postgres
#      curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash -
#      source ~/.bashrc
#      nvm install node
#      nvm install 13.8.0
#      npm install -g pm2 
#      npm install
#      npm run build
#      pm2 stop default
#      pm2 start npm -- start